# Milestones data
# Format: { "Project Name": [ ("Month Day", Type, Description, Complete), ... ] }
# Type: "A" = Activity, "D" = Deliverable
# Complete: True / False

milestones = {
    "Masters Project AgentVis CLI Design": [
        ("May 4", "A", "Scope (Design)", True),
        ("May 11", "A", "Choose techniques (Design)", True),
        ("May 18", "D", "Choose techniques (Design)", False),
        ("May 22", "D", "Draft Intro (Writeup)", False),
        ("May 25", "A", "Choose techniques (Design)", False),
        ("Jun 1", "D", "TUI version (Build)", False),
        ("May 25", "A", "Draft Related Work (Writeup)", False),
        ("Jun 1", "A", "Implement (Build)", False),
        ("Jun 1", "A", "Draft Related Work (Writeup)", False),
        ("Jun 8", "A", "Implement (Build)", False),
        ("Jun 8", "A", "Recruit", False),
        ("Jun 8", "A", "Draft Related Work (Writeup)", False),
        ("Jun 15", "D", "Finish Prototype", False),
        ("Jun 15", "D", "Finish Recruitment", False),
        ("Jun 15", "A", "Stage 1 Study", False),
        ("Jun 15", "D", "Finish drafts of Intro/RW (Writeup)", False),
        ("Jun 15", "D", "Call 2 or 3-stage design based on other projects", False),
        ("Jun 22", "A", "Iterate (Build)", False),
        ("Jun 22", "A", "Recruit", False),
        ("Jun 22", "A", "Methods (Writeup)", False),
        ("Jun 29", "D", "Finish Prototype v2", False),
        ("Jun 29", "D", "Finish Second Recruitment", False),
        ("Jun 29", "A", "Stage 2 Study", False),
        ("Jun 29", "A", "Methods and Results (Writeup)", False),
        ("Jul 6", "A", "Iterate (Build)", False),
        ("Jul 6", "A", "Recruit", False),
        ("Jul 6", "A", "Methods and Results (Writeup)", False),
        ("Jul 13", "D", "Finish Prototype v3", False),
        ("Jul 13", "D", "Finish Experiment Recruitment", False),
        ("Jul 13", "A", "Stage 3 Controlled Experiment", False),
        ("Jul 13", "A", "Methods and Results (Writeup)", False),
        ("Jul 20", "A", "BUFFER for Studies", False),
        ("Jul 20", "D", "Methods and Results (Writeup)", False),
        ("Jul 20", "A", "Discussion (Writeup)", False),
        ("Jul 27", "A", "BUFFER Week", False),
        ("Jul 27", "D", "Discussion (Writeup)", False),
        ("Aug 3", "D", "Paper draft complete", False),
        ("Aug 3", "A", "Edits and Supplementary (Writeup)", False),
        ("Aug 10", "A", "Edits and Supplementary (Writeup)", False),
        ("Aug 17", "A", "Edits and Supplementary (Writeup)", False),
        ("Aug 24", "A", "Edits and Supplementary (Writeup)", False),
    ],
    "Project Preconsult": [
        ("Apr 4", "A", "Arrange meeting with Fanny and Alex, look into REB status/renewal, clean up final direction", True),
        ("Apr 20", "A", "Write up design workshop method and results", True),
        ("Apr 20", "D", "Renew REB / make necessary revisions", True),
        ("Apr 27", "D", "Finish writing up design workshop method and results", True),
        ("Apr 30", "D", "Design stage 2 study / recruitment strategies", True),
        ("Apr 30", "D", "Refine methods and instruments", False),
        ("Jun 1", "A", "Run study (approximate)", False),
        ("Jun 15", "A", "Analyze and write up results", False),
        ("Jun 22", "D", "Paper draft complete", False),
        ("Sep 1", "D", "Submit to CHI", False),
    ],
    "Project Design Space": [
        ("May 11", "D", "Milestones and Capacity Meeting/Decisions", True),
        ("May 18", "A", "Leping: RW; Jeb: Formative Study rework and Intro draft", False),
        ("May 22", "D", "Draft Intro (Writeup)", False),
        ("May 25", "A", "Leping: RW; Jeb: Formative Study rework", False),
        ("Jun 1", "D", "Intro, RW, Formative Study drafts", False),
        ("Jun 8", "A", "Conceptualize lit. review changes and find exemplars; create expert review protocol", False),
        ("Jun 15", "A", "Conceptualize lit. review changes and find exemplars; create expert review protocol", False),
        ("Jun 22", "A", "Write lit. review draft; recruit experts", False),
        ("Jun 29", "A", "Write lit. review draft; recruit experts", False),
        ("Jul 6", "D", "Literature Review Draft", False),
        ("Jul 13", "A", "Execute expert review/validation study", False),
        ("Jul 20", "A", "Analyze and write up results", False),
        ("Jul 27", "A", "Analyze and write up results", False),
        ("Aug 3", "D", "Paper draft complete", False),
        ("Sep 1", "D", "Submit to CHI", False),
    ],
}
